services:
  db:
    image: postgres:${SOFTWARE_VERSION_TAG}
    restart: always
    networks:
      - db-network
    #command: -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
 
  pgadmin4:
    image: elestio/pgadmin:${SOFTWARE_VERSION_TAG}
    restart: always
    networks:
      - db-network
    depends_on:
      - db
    environment:
        PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
        PGADMIN_LISTEN_PORT: 8080
    ports:
        - "8080:8080"
    volumes:
        - ./servers.json:/pgadmin4/servers.json
 
networks:
  db-network:
volumes:
  pgdata: